[package]
name = "xd"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
fltk = "1.4.4"
wry = { version = "0.28.3", default-fratures = false }


[profile.release]
strip = true
opt-level = "s"
lto = true
codegen-units = 1
