[package]
name = "xd"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
deno_bindgen = "0.8.1"
serde = { version = "1", features = ["derive"] }
screenshoter = "0.1.1"
wry = { path = "wry" }
native-dialog = "0.6.4"
image = "0.24.6"


[profile.release]
strip = true
opt-level = "s"
lto = true
codegen-units = 1
