[package]
name = "xd"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
captrs2 = "0.2.2"
dialog-box = "0.1.0"
once_cell = "1.18.0"
screenshots = "0.6.0"
wry = { version = "0.28.3", default-fratures = false }


[profile.release]
strip = true
opt-level = "s"
lto = true
codegen-units = 1
