[package]
name = "xd"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
deno_bindgen = "0.8.1"
serde = { version = "1", features = ["derive"] }
wry = { version = "0.28.3", default-fratures = false }
serde_json = "1.0.96"
screenshoter = "0.1.1"
screenshots = "0.6.0"
captrs2 = "0.2.2"
once_cell = "1.18.0"


[profile.release]
strip = true
opt-level = "s"
lto = true
codegen-units = 1
