[package]
name = "xd"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wry = "0.31.1"
deno_bindgen = "0.8.1"
screenshoter = "0.1.1"
serde = { version = "1", features = ["derive"] }


[profile.release]
strip = true
opt-level = "s"
lto = true
codegen-units = 1
